### ISSUE TITLE
Crawler properties does not work

### ISSUE THREAD

**Issue by datagutten** [jodal/comics#429]
Overriding the properties in CrawlerBase does not work. Properties like history_capable_date always use the default value from CrawlerBase even if they are overridden in a Crawler class.
It works if I remove the type hints, but I have not found any way to make it work with type hints.

https://github.com/jodal/comics/blob/899c2ac36d2c9bab913ff2373c420401eaec0017/comics/aggregator/crawler.py#L80

**Comment by datagutten** [comment]
It seems like the solution is to add the `@dataclass` decorator to all Crawler classes and add type hints to the properties, like this example from the "lunchtu" crawler:
```
@dataclass
class Crawler(CrawlerBase):
    history_capable_days: int = 20
    schedule: str = "Mo,Tu,We,Th,Fr"
    time_zone: str = "Europe/Oslo"
```
With these changes, history capability work as it should, and the status page show the correct schedule:
![image](https://user-images.githubusercontent.com/715898/169367316-9924cfb1-d1e8-4850-a4e3-11ebc5fa33ca.png)

**Comment by jodal** [comment]
You're right. According to https://docs.python.org/3/library/dataclasses.html#inheritance, subclasses of dataclasses also need the `@dataclass` decorator.

I'd consider switching from dataclasses to [pydantic](https://pydantic-docs.helpmanual.io/), which should only require changes to the `CrawlerBase` class. Then we might also get better validation of the data specified in the subclasses.
