### ISSUE TITLE
Add comic author's comic text

### ISSUE THREAD

**Issue by canidae** [jodal/comics#65]
For XKCD the "alt" (or mouseover) text is displayed alongside the comic.
Certain other comics, such as "Scandinavia and the World" and "Nerf Now" also got some descriptive text for the comic, it would be nice if this text also is displayed next to the comic.

**Comment by jodal** [comment]
- [x] XKCD
- [x] SATW
- [x] Nerf Now (d016291b0ae0d2b19d007a7ade78d3d0d769327f)
